### ISSUE TITLE
pull到1.5.1了后，运行报错，卸载原来的在运行还是报错。。。

### ISSUE THREAD

**Issue by cxmmxc** [blackbbc/Tucao#19]
没看出来哪里越界了。。。
```at me.sweetll.tucao.business.home.MainActivity.checkUpdate(MainActivity.kt:516)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at me.sweetll.tucao.business.home.MainActivity.initView(MainActivity.kt:221)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at me.sweetll.tucao.base.BaseActivity.onCreate(BaseActivity.kt:24)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.Activity.performCreate(Activity.java:6357)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.ActivityThread.access$1000(ActivityThread.java:156)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.os.Handler.dispatchMessage(Handler.java:102)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.os.Looper.loop(Looper.java:157)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.ActivityThread.main(ActivityThread.java:5637)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at java.lang.reflect.Method.invoke!(Native method)
11-08 17:38:46.629 1597-1597/? A/art: art/runtime/runtime.cc:366]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366] Pending exception java.lang.ArrayIndexOutOfBoundsException: length=490; index=1613
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void me.sweetll.tucao.business.home.MainActivity.checkUpdate(boolean) (MainActivity.kt:516)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void me.sweetll.tucao.business.home.MainActivity.initView(android.os.Bundle) (MainActivity.kt:221)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void me.sweetll.tucao.base.BaseActivity.onCreate(android.os.Bundle) (BaseActivity.kt:24)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6357)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1108)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2436)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2543)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.ActivityThread.access$1000(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:156)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1407)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.os.Looper.loop() (Looper.java:157)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5637)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:746)
11-08 17:38:46.630 1597-1597/? A/art: art/runtime/runtime.cc:366]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:636)```

**Comment by blackbbc** [comment]
这是个bool值，我也没看出来哪里越界了。。。

**Comment by cxmmxc** [comment]
@blackbbc 你那没报这个错么。。。我现在为了运行把update方法给注了。。。

**Comment by blackbbc** [comment]
@cxmmxc 没毛病，至少从友盟上报的错误来看没有这个错误，大概3000+用户吧。
你先注释着吧。
