### ISSUE TITLE
留言板拉到有图时闪退

### ISSUE THREAD

**Issue by rubnet** [blackbbc/Tucao#24]
#######RuntimeEnvironmentInformation#######
crash time=2018-03-15 13:40:44.817
model=ZUK Z2121
android version=8.0.0(26)
brand=ZUK
manufacturer=ZUK
board=QC_Reference_Phone
hardware=qcom
device=z2_row
version name=1.1.5
supported_abis=arm64-v8a & armeabi-v7a & armeabi
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: me.sweetll.tucao, PID: 26214
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1001)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:968)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:918)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:839)
	at me.sweetll.tucao.widget.d$a.a(GlideImageGetter.kt:46)
	at me.sweetll.tucao.widget.d$a.a(GlideImageGetter.kt:35)
	at com.bumptech.glide.f.f.a(SingleRequest.java:542)
	at com.bumptech.glide.f.f.a(SingleRequest.java:516)
	at com.bumptech.glide.c.b.j.b(EngineJob.java:184)
	at com.bumptech.glide.c.b.j$b.handleMessage(EngineJob.java:288)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6654)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by blackbbc** [comment]
这个bug我是知道的。。。
我以为没人用客户端了所以就没修了

**Comment by rubnet** [comment]
令人窒息
